### ISSUE TITLE
t-coffee dependency not installed error

### ISSUE THREAD

**Issue by shtist** [TGAC/earlham-galaxytools#100]
I have installed the all the tools for GeneSeqToFamily to my locala galaxy server.
The problem is when I install the t-coffee it shows dependency error "The following tool dependencies are required by the current repository. t_coffee version none..." and so on.
So I checked to confirm the dependency installation via Conda.
However, the t-coffee dependency doesn't installed automatically.
What is this t-coffee dependency and where can I find?

I have tried to install the version 11.0.8 and 11.0.8_1 separately and together to test dependency but the error doesn't go away.
Also I tried to test workflow with test data and the step is stucked at t-coffee procedure as I expeceted.
Could you resolve the dependency error?
I used galaxy toolshed to install the repositories.
I double checked the tool versions in github.

Many thanks,

**Comment by nsoranzo** [comment]
@shtist Can you check a few things, please?
- Which Galaxy version are you using? Visiting http://YOUR_GALAXY_SERVER/api/version should tell you this
- If you click "Manage installed tools" in the Galaxy "Admin" interface and search for t_coffee, do you find a row with:

  t_coffee | T-Coffee | earlhaminst | a91be6005274 | Installed | toolshed.g2.bx.psu.edu

- If you click "Manage Tool Dependencies" in the Galaxy "Admin" interface and search for T-Coffee, what do you find? If the row doesn't end with a green tick symbol, try to reinstall the dependency:
  - select the corresponding checkbox and click on "Uninstall checked dependencies using Conda"
  - then select it again and click "Install checked dependencies using Conda"

If that doesn't work, have a look at the Galaxy logs produced during the dependency installation. Also check the installed conda version, I'd recommend to have 4.3.32 (I can help you with that, if needed).

**Comment by shtist** [comment]
1. galaxy version  17.09
2. t_coffee | T-Coffee | earlhaminst | a91be6005274 | Installed | toolshed.g2.bx.psu.edu --> installed
3. green icon checked but it seems Conda cannot install dependencies.
    I checked the status while installing t_coffee. The status showed "installing dependencies" --> "Installed". But when I click "Manage Tool Dependencies" (checked t_coffee green icon) and Dependency Resolver Details of t_coffee shows "dependency not resolved" with red X icon.
4. default conda version (installed using sh run.sh) : 4.3.24

So far, I've setup galaxy toolshed only using web browser (http://localhost:8080) and I've never used conda mannually while install other dependencies (ex. NCBI Blast + and its binaries and so on). Could you tell me how to upgrade Conda from default version to version 4.3.32 and install t-coffee dependencies.

Many thanks

**Comment by nsoranzo** [comment]
To update conda:
```
$ cd YOUR_GALAXY_DIR
$ ./database/dependencies/_conda/bin/conda install conda=4.3.33
```

Then, to reinstall the t-coffee dependencies you can follow my instructions above (third point).

**Comment by shtist** [comment]
I have updated conda=4.3.33 and reinstalled t_coffee a91be6005274 but the result is same as before.

green icon checked but it seems Conda cannot install dependencies.
I checked the status while installing t_coffee. The status showed "installing dependencies" --> "Installed". But when I click "Manage Tool Dependencies" (checked t_coffee green icon) and Dependency Resolver Details of t_coffee shows "dependency not resolved" with red X icon.

What should I do next. Help me, please.

**Comment by nsoranzo** [comment]
I think my explanation above was not clear enough, you have reinstalled the tool from the ToolShed, while I suggested to reinstall the tool dependency. Try to:
- click "Manage Tool Dependencies" in the left menu on the Galaxy "Admin" interface
- search for T-Coffee
- select the corresponding checkbox on the left and click on "Uninstall checked dependencies using Conda" at the bottom of the page (this may take a while)
- then select the T-Coffee checkbox again and click "Install checked dependencies using Conda" (this will also take a while).
