### ISSUE TITLE
Move blast_parser inside hcluster_sg .

### ISSUE THREAD

**Issue by nsoranzo** [TGAC/earlham-galaxytools#3]
I guess there is no use case for the `blast_parser` tool outside a `hcluster_sg` pipeline, what about moving its files inside `hcluster_sg` directory and release them inside the same Tool Shed repository?

**Comment by anilthanki** [comment]
Don't think it will make sense, as it can't be officially part of BLAST or hcluster_sg, It uses BLAST output to generate hcluster_sg input, but not necessary tool for both
