### ISSUE TITLE
hcluster_sg parser issue

### ISSUE THREAD

**Issue by blsfoxfox** [TGAC/earlham-galaxytools#82]
Hi,

I came across an error while running hcluster_sg parser:
Traceback (most recent call last):
  File "hcluster_sg_parser.py", line 36, in <module>
    main()
  File "hcluster_sg_parser.py", line 24, in main
    (cluster_id, n_ids, id_list) = line.split('\t')
ValueError: too many values to unpack

The command I was running:
python hcluster_sg_parser.py -m 1 allspecies_cluster allspecies_cluster_new_discard

Could you please help me to solve this?

Thanks,

**Comment by nsoranzo** [comment]
@blsfoxfox Are you using `hcluster` without option `-c` ("only find single-linkage clusters")? In that case `hcluster` produces an output with more columns, which may cause the above error. For our GeneSeqToFamily workflow we always use `-c`, but I can easily fix `hcluster_sg_parser` to deal with this.

**Comment by blsfoxfox** [comment]
Hi Dr. Soranzo,

Thanks for your quick response and the fix of hcluster_sg_parser!

Best regards,

Lisui Bao
