### ISSUE TITLE
how to identity 1:1 orthologs after hcluster_sg_parser?

### ISSUE THREAD

**Issue by blsfoxfox** [TGAC/earlham-galaxytools#83]
Hi Dr. Soranzo,

Could you please provide some suggestions on how to how to identity 1:1 orthologs after the running of hcluster_sg_parser? What I was doing is import the output files into excel and count the gene numbers and names of different species. Maybe you have an easier way to solve this?

Thanks,

**Comment by anilthanki** [comment]
Hi

I think thats the easiest way at the moment, but we might think of adding/modifying this script to give a bit of analytics about gene family type i.e. 1:1 orthologs, 1:many orthologs and paralogs etc

Thanks

**Comment by blsfoxfox** [comment]
Got it, thanks for your response!

Best,

blsfoxfox
