### ISSUE TITLE
Export datasets to cluster tool  -  error

### ISSUE THREAD

**Issue by GuyReeves** [TGAC/earlham-galaxytools#87]
Hi 

I am trying to use 'Export datasets to cluster' tool  on a private galaxy instance 
I am getting the error 

I am guessing that I need to specify a file with the prefix in but in the toolshed there is no information about how to do this or where to place the file.

Can you help 
Cheers 

Guy

Fatal error: Exit code 2 ()
Usage: export_to_cluster.py [options]

export_to_cluster.py: error: Directory prefix cannot be empty

**Comment by nsoranzo** [comment]
@GuyReeves Sorry for the very late reply on this, instruction on how to solve this are now at https://github.com/TGAC/earlham-galaxytools/blob/master/tools/export_to_cluster/README.rst
