### ISSUE TITLE
ete lineage generator tsv headers and manual rank selection

### ISSUE THREAD

**Issue by bernt-matthias** [TGAC/earlham-galaxytools#95]
Found some problems in the recently merged https://github.com/TGAC/earlham-galaxytools/pull/90: 

- I realised that manual rank selection does not work. I get an error:  `'SelectToolParameterWrapper' object is not iterable`
- The ete lineage generator produces a tsv file. The display in Galaxy suggests that the first line is taken as header -- but I guess that its just shown twice: once as header and again as data line.  What would be the way to leave the header display empty (just numbering the columns 1,2,3...) or to label it with useful column names (input, rank1, ...)?

**Comment by nsoranzo** [comment]
For the second point, I think that:
- the output format should be `tabular`, `tsv` is only required for datasets with tabs inside double quotes
- there should be a header line, guessing what rank is in each column is not user-friendly.

**Comment by bernt-matthias** [comment]
Ok. By using tabular I get numbered columns, but how do I set the column names to the ranks?

**Comment by nsoranzo** [comment]
Add a header line as first line of the output file?

**Comment by bernt-matthias** [comment]
How can I mark the header line as header? I already tried: 
- `#` (with and without space)
- `>`
- using `"` at the start and end of the line
- and of course no mark

In any case the first line is shown as data.

**Comment by nsoranzo** [comment]
@bernt-matthias I think that's fixed, correct?

**Comment by bernt-matthias** [comment]
The header is still shown twice in Galaxy (but only one `#` line is in the data). Tested on dev with the latest tool version. 

![screenshot from 2018-05-09 15-35-07](https://user-images.githubusercontent.com/25689525/39817505-a37928de-539e-11e8-9c04-e748ad317480.png)

I've noticed that I forgot to change the tool version in my PRs. So I can not change the version if multiple are installed. Needs a fix.

**Comment by nsoranzo** [comment]
Well, that's probably a Galaxy bug, right?

**Comment by bernt-matthias** [comment]
Just remembered: https://github.com/galaxyproject/galaxy/issues/5150 .. maybe the issue is to unspecific?

**Comment by nsoranzo** [comment]
Yes, let's close this one and fix it in Galaxy.
